[versions]
detekt = "1.20.0"
kotlin = "1.6.21"
pluginPublish = "1.2.1"
versionCheck = "0.42.0"
agp = "7.2.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck" }
androidApplication = { id = "com.android.application", version.ref = "agp" }

[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

junit = "junit:junit:4.13.2"
